export const FETCH_USERDATA_REQUEST = 'FETCH_USERDATA_REQUEST';
export const FETCH_USERDATA_SUCCESS = 'FETCH_USERDATA_SUCCESS';
export const FETCH_USERDATA_ERROR = 'FETCH_USERDATA_ERROR';

export const FETCH_TRENDS_REQUEST = 'FETCH_TRENDS_REQUEST';
export const FETCH_TRENDS_SUCCESS = 'FETCH_TRENDS_SUCCESS';
export const FETCH_TRENDS_ERROR = 'FETCH_TRENDS_ERROR';